/* File Extension Table */

DROP TABLE IF EXISTS file_extension;
CREATE TABLE file_extension (
    file_extension_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    file_extension_name VARCHAR(100) NOT NULL,
    file_extension VARCHAR(10) NOT NULL,
    file_type_id INT NOT NULL,
    file_type_name VARCHAR(100) NOT NULL,
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_log_by INT UNSIGNED DEFAULT 1,
    FOREIGN KEY (last_log_by) REFERENCES user_account(user_account_id)
);

CREATE INDEX file_extension_index_file_extension_id ON file_extension(file_extension_id);
CREATE INDEX file_extension_index_file_type_id ON file_extension(file_type_id);

INSERT INTO file_extension (file_extension_id, file_extension_name, file_extension, file_type_id, file_type_name, last_log_by) VALUES
(1, 'AIF', 'aif', 1, 'Audio', 1),
(2, 'CDA', 'cda', 1, 'Audio', 1),
(3, 'MID', 'mid', 1, 'Audio', 1),
(4, 'MIDI', 'midi', 1, 'Audio', 1),
(5, 'MP3', 'mp3', 1, 'Audio', 1),
(6, 'MPA', 'mpa', 1, 'Audio', 1),
(7, 'OGG', 'ogg', 1, 'Audio', 1),
(8, 'WAV', 'wav', 1, 'Audio', 1),
(9, 'WMA', 'wma', 1, 'Audio', 1),
(10, 'WPL', 'wpl', 1, 'Audio', 1),
(11, '7Z', '7z', 2, 'Compressed', 1),
(12, 'ARJ', 'arj', 2, 'Compressed', 1),
(13, 'DEB', 'deb', 2, 'Compressed', 1),
(14, 'PKG', 'pkg', 2, 'Compressed', 1),
(15, 'RAR', 'rar', 2, 'Compressed', 1),
(16, 'RPM', 'rpm', 2, 'Compressed', 1),
(17, 'TAR.GZ', 'tar.gz', 2, 'Compressed', 1),
(18, 'Z', 'z', 2, 'Compressed', 1),
(19, 'ZIP', 'zip', 2, 'Compressed', 1),
(20, 'BIN', 'bin', 3, 'Disk and Media', 1),
(21, 'DMG', 'dmg', 3, 'Disk and Media', 1),
(22, 'ISO', 'iso', 3, 'Disk and Media', 1),
(23, 'TOAST', 'toast', 3, 'Disk and Media', 1),
(24, 'VCD', 'vcd', 3, 'Disk and Media', 1),
(25, 'CSV', 'csv', 4, 'Data and Database', 1),
(26, 'DAT', 'dat', 4, 'Data and Database', 1),
(27, 'DB', 'db', 4, 'Data and Database', 1),
(28, 'DBF', 'dbf', 4, 'Data and Database', 1),
(29, 'LOG', 'log', 4, 'Data and Database', 1),
(30, 'MDB', 'mdb', 4, 'Data and Database', 1),
(31, 'SAV', 'sav', 4, 'Data and Database', 1),
(32, 'SQL', 'sql', 4, 'Data and Database', 1),
(33, 'TAR', 'tar', 4, 'Data and Database', 1),
(34, 'XML', 'xml', 4, 'Data and Database', 1),
(35, 'EMAIL', 'email', 5, 'Email', 1),
(36, 'EML', 'eml', 5, 'Email', 1),
(37, 'EMLX', 'emlx', 5, 'Email', 1),
(38, 'MSG', 'msg', 5, 'Email', 1),
(39, 'OFT', 'oft', 5, 'Email', 1),
(40, 'OST', 'ost', 5, 'Email', 1),
(41, 'PST', 'pst', 5, 'Email', 1),
(42, 'VCF', 'vcf', 5, 'Email', 1),
(43, 'APK', 'apk', 6, 'Executable', 1),
(44, 'BAT', 'bat', 6, 'Executable', 1),
(45, 'BIN', 'bin', 6, 'Executable', 1),
(46, 'CGI', 'cgi', 6, 'Executable', 1),
(47, 'PL', 'pl', 6, 'Executable', 1),
(48, 'COM', 'com', 6, 'Executable', 1),
(49, 'EXE', 'exe', 6, 'Executable', 1),
(50, 'GADGET', 'gadget', 6, 'Executable', 1),
(51, 'JAR', 'jar', 6, 'Executable', 1),
(52, 'WSF', 'wsf', 6, 'Executable', 1),
(53, 'FNT', 'fnt', 7, 'Font', 1),
(54, 'FON', 'fon', 7, 'Font', 1),
(55, 'OTF', 'otf', 7, 'Font', 1),
(56, 'TTF', 'ttf', 7, 'Font', 1),
(57, 'AI', 'ai', 8, 'Image', 1),
(58, 'BMP', 'bmp', 8, 'Image', 1),
(59, 'GIF', 'gif', 8, 'Image', 1),
(60, 'ICO', 'ico', 8, 'Image', 1),
(61, 'JPG', 'jpg', 8, 'Image', 1),
(62, 'JPEG', 'jpeg', 8, 'Image', 1),
(63, 'PNG', 'png', 8, 'Image', 1),
(64, 'PS', 'ps', 8, 'Image', 1),
(65, 'PSD', 'psd', 8, 'Image', 1),
(66, 'SVG', 'svg', 8, 'Image', 1),
(67, 'TIF', 'tif', 8, 'Image', 1),
(68, 'TIFF', 'tiff', 8, 'Image', 1),
(69, 'WEBP', 'webp', 8, 'Image', 1),
(70, 'ASP', 'asp', 9, 'Internet Related', 1),
(71, 'ASPX', 'aspx', 9, 'Internet Related', 1),
(72, 'CER', 'cer', 9, 'Internet Related', 1),
(73, 'CFM', 'cfm', 9, 'Internet Related', 1),
(74, 'CGI', 'cgi', 9, 'Internet Related', 1),
(75, 'PL', 'pl', 9, 'Internet Related', 1),
(76, 'CSS', 'css', 9, 'Internet Related', 1),
(77, 'HTM', 'htm', 9, 'Internet Related', 1),
(78, 'HTML', 'html', 9, 'Internet Related', 1),
(79, 'JS', 'js', 9, 'Internet Related', 1),
(80, 'JSP', 'jsp', 9, 'Internet Related', 1),
(81, 'PART', 'part', 9, 'Internet Related', 1),
(82, 'PHP', 'php', 9, 'Internet Related', 1),
(83, 'PY', 'py', 9, 'Internet Related', 1),
(84, 'RSS', 'rss', 9, 'Internet Related', 1),
(85, 'XHTML', 'xhtml', 9, 'Internet Related', 1),
(86, 'KEY', 'key', 10, 'Presentation', 1),
(87, 'ODP', 'odp', 10, 'Presentation', 1),
(88, 'PPS', 'pps', 10, 'Presentation', 1),
(89, 'PPT', 'ppt', 10, 'Presentation', 1),
(90, 'PPTX', 'pptx', 10, 'Presentation', 1),
(91, 'ODS', 'ods', 11, 'Spreadsheet', 1),
(92, 'XLS', 'xls', 11, 'Spreadsheet', 1),
(93, 'XLSM', 'xlsm', 11, 'Spreadsheet', 1),
(94, 'XLSX', 'xlsx', 11, 'Spreadsheet', 1),
(95, 'BAK', 'bak', 12, 'System Related', 1),
(96, 'CAB', 'cab', 12, 'System Related', 1),
(97, 'CFG', 'cfg', 12, 'System Related', 1),
(98, 'CPL', 'cpl', 12, 'System Related', 1),
(99, 'CUR', 'cur', 12, 'System Related', 1),
(100, 'DLL', 'dll', 12, 'System Related', 1),
(101, 'DMP', 'dmp', 12, 'System Related', 1),
(102, 'DRV', 'drv', 12, 'System Related', 1),
(103, 'ICNS', 'icns', 12, 'System Related', 1),
(104, 'INI', 'ini', 12, 'System Related', 1),
(105, 'LNK', 'lnk', 12, 'System Related', 1),
(106, 'MSI', 'msi', 12, 'System Related', 1),
(107, 'SYS', 'sys', 12, 'System Related', 1),
(108, 'TMP', 'tmp', 12, 'System Related', 1),
(109, '3G2', '3g2', 13, 'Video', 1),
(110, '3GP', '3gp', 13, 'Video', 1),
(111, 'AVI', 'avi', 13, 'Video', 1),
(112, 'FLV', 'flv', 13, 'Video', 1),
(113, 'H264', 'h264', 13, 'Video', 1),
(114, 'M4V', 'm4v', 13, 'Video', 1),
(115, 'MKV', 'mkv', 13, 'Video', 1),
(116, 'MOV', 'mov', 13, 'Video', 1),
(117, 'MP4', 'mp4', 13, 'Video', 1),
(118, 'MPG', 'mpg', 13, 'Video', 1),
(119, 'MPEG', 'mpeg', 13, 'Video', 1),
(120, 'RM', 'rm', 13, 'Video', 1),
(121, 'SWF', 'swf', 13, 'Video', 1),
(122, 'VOB', 'vob', 13, 'Video', 1),
(123, 'WEBM', 'webm', 13, 'Video', 1),
(124, 'WMV', 'wmv', 13, 'Video', 1),
(125, 'DOC', 'doc', 14, 'Word Processor', 1),
(126, 'DOCX', 'docx', 14, 'Word Processor', 1),
(127, 'PDF', 'pdf', 14, 'Word Processor', 1),
(128, 'RTF', 'rtf', 14, 'Word Processor', 1),
(129, 'TEX', 'tex', 14, 'Word Processor', 1),
(130, 'TXT', 'txt', 14, 'Word Processor', 1),
(131, 'WPD', 'wpd', 14, 'Word Processor', 1);

/* ----------------------------------------------------------------------------------------------------------------------------- */